---
- name: Setup Node.js and Wavesurfer.js
  hosts: all
  become: yes

  tasks:
    - name: Update and upgrade yum packages
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Node.js
      yum:
        name: nodejs
        state: present

    - name: Install npm
      yum:
        name: npm
        state: present

    - name: Install PM2
      npm:
        name: pm2
        global: yes

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Create project directory
      file:
        path: /var/www/wavesurfer-app
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Create public directory
      file:
        path: /var/www/wavesurfer-app/public
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Copy application files
      copy:
        src: /home/ec2-user/project/
        dest: /var/www/wavesurfer-app/
        owner: ec2-user
        group: ec2-user
        mode: '0755'
        remote_src: yes

    - name: Copy public files
      copy:
        src: /home/ec2-user/project/public/
        dest: /var/www/wavesurfer-app/public/
        owner: ec2-user
        group: ec2-user
        mode: '0755'
        remote_src: yes

    - name: Ensure correct permissions for project directory
      file:
        path: /var/www/wavesurfer-app
        state: directory
        owner: ec2-user
        group: ec2-user
        recurse: yes
        mode: '0755'

    - name: Install project dependencies
      command: npm install
      args:
        chdir: /var/www/wavesurfer-app/

    - name: Start the application with PM2
      command: pm2 start app.js
      args:
        chdir: /var/www/wavesurfer-app/

    - name: Setup PM2 to start on boot
      command: pm2 startup
      args:
        chdir: /var/www/wavesurfer-app/

    - name: Save PM2 process list
      command: pm2 save
      args:
        chdir: /var/www/wavesurfer-app/

    - name: Configure Nginx
      copy:
        content: |
          server {
              listen 80;

              server_name _;

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }

              location /uploads/ {
                  alias /var/www/wavesurfer-app/uploads/;
              }
          }
        dest: /etc/nginx/conf.d/wavesurfer.conf

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
